plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - # github
    - '@semantic-release/github'
    - {}
branches:
  - release
  - 'release/+([0-9])?(.{+([0-9]),x}).x'