plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - # github
    - '@semantic-release/github'
    - {}
  - # bump
    - '@semantic-release/exec'
    - publishCmd: "echo '${nextRelease.version}' > version_number"
  - # commit
    - '@semantic-release/git'
    - assets: 
        - version_number
      message: "chore(release): ${nextRelease.version} [skip ci]"

branches:
  - release
  - 'release/+([0-9])?(.{+([0-9]),x}).x'