name: Release
on: #[push]
  push:
    branches:
      - 'releases'
      - 'release/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - run: pip install python-semantic-release

      - run: |
          semantic-release version
          semantic-release changelog --post
          git push --follow-tags
          